name = "TwoLayerDirectNumericalShenanigans"
uuid = "40aaee9f-3595-48be-b36c-f1067009652f"
authors = ["Josef Bisits <jbisits@gmail.com>"]
version = "0.7.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GibbsSeaWater = "9a22fb26-0b63-4589-b28e-8f9d0b5c3d05"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Oceanostics = "d0ccf422-c8fb-49b5-a76d-74acdde946ac"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[extensions]
TLDNSMakieExt = "CairoMakie"

[compat]
CUDA = "5"
CairoMakie = "0.10, 0.12"
GibbsSeaWater = "0.1"
JLD2 = "0.4, 0.5"
NCDatasets = "0.12, 0.13, 0.14"
Oceananigans = "0.89, 0.90, 0.91, 0.92, 0.93, 0.94"
Oceanostics = "0.11, 0.12, 0.13, 0.14"
Reexport = "1.2"
SeawaterPolynomials = "0.3"
SpecialFunctions = "2"
StatsBase = "0.34"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
